### ISSUE TITLE
Likely broken by new canary update

### ISSUE THREAD

**Issue by SheepCommander** [RazerMoon/userNotifs#5]
Settings still there
![image](https://user-images.githubusercontent.com/66646514/148942814-3a709642-4e58-41b4-8999-0532be28f357.png)

But not the option
![image](https://user-images.githubusercontent.com/66646514/148942769-c3f8cfee-f60f-47e2-930c-2565ef100ce4.png)

**Comment by RazerMoon** [comment]
Should be working now, dcord update broke as always. Fix be wacky tho, so try right clicking a second time if it doesn't work initially.

> Dev stuff: I don't think I can force the module to load early, so I just set up an event listener and fire the patch after someone right clicks. Force update also acting wacky.

**Comment by ghost** [comment]
broken for me
